/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{njk,md,html,js}",
    "./content/**/*.md",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#6f4253",
        "nav-purple": "#8e5a6d",
        "on-secondary-fixed-variant": "#2c673c",
        "primary-fixed": "#f8bbd0",
        "surface-container-high": "#e9e3cc",
        "on-tertiary-container": "#634668",
        "secondary": "#2c673c",
        "surface-variant": "#e3ddc5",
        "error": "#b02500",
        "on-secondary-container": "#215d33",
        "error-container": "#f95630",
        "outline": "#7a7768",
        "error-dim": "#b92902",
        "secondary-fixed-dim": "#a4e3ad",
        "on-error": "#ffefec",
        "on-primary-container": "#623648",
        "surface-tint": "#7d4d5f",
        "inverse-surface": "#100e05",
        "on-primary-fixed-variant": "#6c3f51",
        "on-surface-variant": "#5f5c4d",
        "primary-container": "#f8bbd0",
        "surface-container-low": "#f7f1dc",
        "surface-container": "#eee8d3",
        "inverse-on-surface": "#a19d8c",
        "on-secondary": "#ceffd2",
        "secondary-fixed": "#b2f2bb",
        "on-error-container": "#520c00",
        "on-primary-fixed": "#4b2334",
        "surface": "#fcf6e3",
        "inverse-primary": "#f8bbd0",
        "on-tertiary": "#ffeefd",
        "tertiary-fixed": "#fad3fd",
        "secondary-container": "#b2f2bb",
        "surface-dim": "#dbd5bc",
        "on-secondary-fixed": "#084a22",
        "on-background": "#312f23",
        "tertiary-dim": "#624568",
        "surface-bright": "#fcf6e3",
        "primary": "#7d4d5f",
        "tertiary-fixed-dim": "#ebc5ef",
        "on-tertiary-fixed": "#4f3455",
        "surface-container-highest": "#e3ddc5",
        "on-surface": "#312f23",
        "on-primary": "#ffeff2",
        "outline-variant": "#b2ad9c",
        "primary-fixed-dim": "#e9aec3",
        "background": "#fcf6e3",
        "on-tertiary-fixed-variant": "#6d4f72",
        "tertiary-container": "#fad3fd",
        "tertiary": "#6f5174",
        "surface-container-lowest": "#ffffff",
        "secondary-dim": "#1f5b31"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        handwritten: ["Caveat", "Gochi Hand", "cursive"],
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
